
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 6;
  public static final int END_BAG = 7;
  public static final int BAG = 3;
  public static final int error = 1;
  public static final int STM_END = 5;
  public static final int LST_COMP = 4;
  public static final int EOF = 0;
  public static final int ASSIGN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "BAG",
  "LST_COMP",
  "STM_END",
  "NUM",
  "END_BAG"
  };
}

